name: Perform merge checks
on: pull_request

jobs:
  macos:
    name: macOS
    runs-on: macos-12
    env:
      CONAN_DEFAULT_PROFILE: ${{ github.workspace }}/config/conan/macos-armv8.profile
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: turtlebrowser/get-conan@main
        with:
          version: 2.0.2  
      - name: Provision
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.MACOS_P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.MACOS_BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Setup
        run: |
          brew update
          brew bundle install --file=config/system/requirements.macos.brew.rb
          conan profile detect
      - name: Build
        env:
          MACOS_APPLE_IDENTITY: ${{ secrets.MACOS_APPLE_IDENTITY }}
          MACOS_APPLE_ID: ${{ secrets.MACOS_APPLE_ID }}
          MACOS_APPLE_PASSWORD: ${{ secrets.MACOS_APPLE_PASSWORD }}
          MACOS_APPLE_TEAM_ID: ${{ secrets.MACOS_APPLE_TEAM_ID }}
        run: |
          conan create modules/juce-conan
          conan install .
          conan build .
          conan export-pkg .
      - name: Test
        run: |
          conan create modules/pluginval-conan
          conan test test peakeater/0.6.3@vvvar/testing
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-macos
          path: build/Release

  windows:
    name: Windows
    runs-on: windows-2022
    env:
      CONAN_DEFAULT_PROFILE: ${{ github.workspace }}/config/conan/windows-x86_64.profile
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: 'recursive'
      - uses: turtlebrowser/get-conan@main
        with:
          version: 2.0.2  
      - name: Setup
        run: |
          choco install config\system\requirements.windows.choco.config
          conan profile detect
      - name: Build
        run: |
          conan create modules\juce-conan
          conan install .
          conan build .
          conan export-pkg .
      - name: Test
        run: |
          conan create modules\pluginval-conan
          conan test test peakeater/0.6.3@vvvar/testing
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-windows
          path: build/Release

  linux:
    name: Linux
    runs-on: ubuntu-20.04
    env:
      CONAN_DEFAULT_PROFILE: ${{ github.workspace }}/config/conan/linux-x86_64.profile
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: turtlebrowser/get-conan@main
        with:
          version: 2.0.2 
      - name: Setup
        run: |
          sudo apt-get update
          sudo xargs -a config/system/requirements.linux.apt.txt apt-get install -y
          conan profile detect
      - name: Build
        run: |
          conan create modules/juce-conan
          conan install .
          conan build .
          conan export-pkg .
      - name: Test
        run: |
          conan create modules/pluginval-conan
          conan test test peakeater/0.6.3@vvvar/testing
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-linux
          path: build/Release