name: Build & Ensure Quality

on: workflow_call

jobs:
  macos:
    name: macOS
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      - uses: extractions/setup-just@v1
        with:
          just-version: 1.13.0
      - name: Setup
        run: npm install
      - name: Test
        run: npm test

  windows:
    name: Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      - uses: extractions/setup-just@v1
        with:
          just-version: 1.13.0
      - name: Setup
        run: npm install
      - name: Test
        run: npm test

  linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      - uses: extractions/setup-just@v1
        with:
          just-version: 1.13.0
      - name: Setup
        run: npm install
      - name: Test
        run: npm test
