name: Make a Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Create Release Draft
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          removeArtifacts: true
          makeLatest: true
          tag: "0.1.5"
