name: Make a Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Publish Release Draft
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Placeholder
        run: echo All good
